# apps and their ports:
# portainer: 8080, jenkins: 8081, gogs: 8082, nexus: 8083, sonarqube: 8084
version: '3'
services:
  # portainer
  portainer:
    image: portainer/portainer
    container_name: "portainer-app"
    network_mode: default
    ports:
      - "8080:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  # jenkins
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    network_mode: default
    user: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_serverdata:/data
    environment:
      JENKINS_HOST_HOME: "/data/jenkins_home"
    ports:
      - "8081:8080"
      - "443:443"
  # gogs git server
  git_server:
    image: gogs/gogs
    container_name: git_server
    network_mode: default
    ports:
     - "8082:3000"
     - "10022:22"
    volumes:
     - gogs_conf:/data
    links:
     - db:mysql
  # sonatype nexus
  nexus:
    image: sonatype/nexus3
    container_name: nexus3
    network_mode: default
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - "8083:8081"
  # sonarqube
  sonarqube:
    container_name: sonarqube
    image: sonarqube
    network_mode: default
    ports:
      - "8084:9000"
    links:
      - db:mysql
    environment:
      - enviDB_USER=cisuer
      - enviDB_PASS=cipass
      - enviDB_NAME=cistack
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
  # common db
  db:
    image: mariadb
    container_name: db
    network_mode: default
    volumes:
      - gogs_conf:/var/lib/mysql
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=cidb
     - MYSQL_USER=ciuser
     - MYSQL_PASSWORD=cipass
volumes:
  portainer_data:
  jenkins_serverdata:
  gogs_conf:
  gogs_data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  nexus-data:
