# apps and their ports:
# portainer: 8080, jenkins: 8081, gogs: 8082, nexus: 8083, sonarqube: 8084
version: '2'
services:
  # portainer
  portainer:
    image: portainer/portainer
    container_name: "portainer-app"
    network_mode: default
    ports:
      - "8080:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    volumes_from:
      - data_container
  # jenkins
  jenkins:
    #image: jenkins/jenkins:latest
    # Using my own jenkins docker image so the docker group id from the docker host
    # can be added to the jenkins user in the container
    image: jenkins-master
    container_name: jenkins
    network_mode: default
    user: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    volumes_from:
      - data_container
    environment:
      JENKINS_HOST_HOME: "/data/jenkins_home"
    ports:
      - "8081:8080"
      - "443:443"
  # gogs git server
  git_gogs:
    image: gogs/gogs
    container_name: git_gogs
    network_mode: default
    ports:
      - "8082:3000"
      - "10022:22"
    volumes_from:
        - data_container
    links:
      - db:mysql
  # common db container
  data_container:
    image: busybox
    container_name: data_container
    network_mode: default
    command: /bin/sh
    volumes:
      - /data
  # sonatype nexus
  nexus:
    image: sonatype/nexus3
    container_name: nexus3
    network_mode: default
    volumes_from:
      - data_container 
    ports:
      - "8083:8081"
  # sonarqube
  sonarqube:
    container_name: sonarqube
    image: sonarqube
    network_mode: default
    ports:
      - "8084:9000"
    links:
      - db:mysql
    environment:
      - enviDB_USER=cisuer
      - enviDB_PASS=cipass
      - enviDB_NAME=cistack
    volumes_from:
      - data_container
  # common db
  db:
    image: mariadb
    container_name: db
    network_mode: default
    volumes:
      - db_data:/var/lib/mysql
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=cistack
     - MYSQL_USER=gogs
     - MYSQL_PASSWORD=gogs
volumes:
  portainer_data:
  jenkins_serverdata:
  db_data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  nexus-data:
