# portainer: 8080, jenkins: 8081, gogs: 8082, nexus: 8083, sonarqube: 8084
version: '2'
services:
  # portainer
  portainer:
    image: portainer/portainer
    container_name: "portainer-app"
    network_mode: default
    ports:
      - "8080:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    volumes_from:
     - portainer_serverdata
  # portainer data container
  portainer_serverdata:
    image: busybox
    container_name: portainer_serverdata
    network_mode: default
    command: /bin/sh
    volumes:
      - /data
  # jenkins
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    network_mode: default
    user: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    volumes_from:
     - jenkins_serverdata
    environment:
      JENKINS_HOST_HOME: "/data/jenkins_home"
    ports:
      - "8081:8080"
      - "443:443"
  # jenkins data container
  jenkins_serverdata:
    image: busybox
    container_name: jenkins_serverdata
    network_mode: default
    command: /bin/sh
    volumes:
      - data/
  git_server:
    image: gogs/gogs
    container_name: git_server
    network_mode: default
    ports:
     - "8082:3000"
     - "10022:22"
    volumes_from:
     - git_serverdata
    links:
     - git_db:mysql
  # gogs data container
  git_serverdata:
    image: busybox
    container_name: git_serverdata
    network_mode: default
    command: /bin/sh
    volumes:
      - /data
  # gogs backend - mariadb
  git_db:
    image: mariadb
    container_name: git_db
    network_mode: default
    volumes_from:
      - git_dbdata
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=gogs
     - MYSQL_USER=gogs
     - MYSQL_PASSWORD=gogs
  # gogs db data container
  git_dbdata:
    image: busybox
    container_name: git_dbdata
    network_mode: default
    command: /bin/sh
    volumes:
      - /var/lib/mysql
  nexus-data:
    image: sonatype/nexus3
    network_mode: default
    entrypoint:
    - /bin/true
  nexus:
    image: sonatype/nexus3
    network_mode: default
    volumes_from:
    - nexus-data
    depends_on:
    - nexus-data
    ports:
    - "8083:8081"
  sonarqube:
    image: sonarqube
    container_name: sonarqube
    ports:
      - "8084:9000"
    depends_on:
     - sonardb
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
    volumes_from:
     - sonarqube_serverdata
  # sonarqube data container
  sonarqube_serverdata:
    image: busybox
    container_name: sonarqube_serverdata
    command: /bin/sh
    volumes:
      - /opt/sonarqube/conf
      - /opt/sonarqube/data
      - /opt/sonarqube/extensions
      - /opt/sonarqube/lib/bundled-plugins
  # artifactory backend - postgres
  sonardb:
    image: docker.bintray.io/postgres:9.5.2
    container_name: sonardb
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    ports:
     - 5432
    volumes_from:
     - sonar_dbdata
  sonar_dbdata:
    image: busybox
    container_name: sonar_dbdata
    command: /bin/sh
    volumes:
      - /var/lib/postgresql/data
